aws-samples/eks-workshop-v2

- .github/PULL_REQUEST_TEMPLATE.md
> Legal verbiage

- website/src/theme/Footer/index.js
add cloudflare analytics snippet
> add cloudflare analytics snippet

- .github/workflows/preview-prod.yaml
- website/docusaurus.config.js
need indexing for a sitemap.xml to enable search #309 
> enable indexing

- environment/workspace/modules/fundamentals/storage/ebs/statefulset-mysql.yaml
- environment/workspace/modules/observability/container-insights/adot/opentelemetrycollector.yaml
- website/docs/automation/gitops/flux/deploy_application.md
- website/docs/autoscaling/workloads/cluster-proportional-autoscaler/index.md
- website/docs/fundamentals/exposing/ingress/adding-ingress.md
- website/docs/fundamentals/managed-node-groups/adding-nodes/index.md
- website/docs/fundamentals/managed-node-groups/affinity/index.md
- website/docs/fundamentals/storage/efs/deployment-with-efs.md
- website/docs/introduction/getting-started/first.md
- website/docs/observability/open-source-metrics/adot.md
- website/docs/observability/open-source-metrics/amp-ws.md
Fixes small typos and issues I had while doing the workshop
> Fix small typos

- website/docs/introduction/getting-started/first.md
> Fixed a typo in line 110 that had a grep command

- website/docs/introduction/setup/your-account.md
There may be cases where the lab environment needs updated after it was created, for example if a new module is introduced or other changes are made. This adds basic instructions to update the environment via the Terraform.
Fixes #
> Instructions to update lab environment

- website/docs/introduction/index.mdx
> Revert video to ReactControls

- website/docs/automation/gitops/argocd/deploy.md
- website/docs/automation/gitops/argocd/update.md
Fixes #319, issue with last PR
> Fix path issue when deploying from the repository

- docs/automated_tests.md
The Description wass innacurate for what to test prior to submit the PR
> Fix Test to be done before PR

- website/docs/introduction/index.mdx
> Spelling mistake

- website/docs/fundamentals/managed-node-groups/taints/implementing-tolerations.md
> Spelling correction

- website/docs/fundamentals/storage/ebs/statefulset.md
Edits to improve grammar, flow and consistency.
Fixes #
> Edits to improve grammar, flow and consistency

- website/docs/networking/index.mdx
adding CFTC video to networking module
> add networking video to workshop

- environment/workspace/manifests/assets/deployment.yaml
- environment/workspace/manifests/carts/deployment.yaml
- environment/workspace/manifests/catalog/configMap.yaml
- environment/workspace/manifests/catalog/deployment.yaml
- environment/workspace/manifests/checkout/deployment.yaml
- environment/workspace/manifests/orders/deployment.yaml
- environment/workspace/manifests/ui/deployment.yaml
- environment/workspace/modules/fundamentals/storage/efs/deployment/deployment.yaml
- environment/workspace/modules/security/sealed-secrets/new-catalog-db.yaml
- website/docs/fundamentals/fargate/enabling.md
- website/docs/fundamentals/storage/efs/deployments.md
- website/docs/security/pod-security-standards/privileged.md
- website/docs/security/sealed-secrets/sealing-secrets.md
Upgrades the retail sample application to 0.4.0 to enable upcoming workshop labs that rely on features.
Fixes #
> Upgrade retail sample application to 0.4.0

- website/docs/introduction/ide.md
- website/docs/introduction/setup/your-account.md
Minor updates to documentation to address issue #481 
Fixes #481 
> Instruction for "Setup in your AWS account" not clear about reference to Cloud9

- website/docs/automation/controlplanes/crossplane/resources.md
> fix kind of kubectl get crossplane rds

- website/docs/fundamentals/managed-node-groups/taints/configuring-taints.md
Update `ensuring every node within the MNG will have the asociated labels and taints configured automatically. ` to `ensuring every node within the MNG will have the associated labels and taints configured automatically. `
> Fixed spelling

- environment/installer.sh
Fixes problem with argocd create app
> update argocd cli version to 2.7.4

- website/docs/automation/gitops/index.mdx
- website/docs/observability/index.mdx
Adds explainer videos from Containers from the Couch. No technical changes.
> add cftc explainers

- test/Dockerfile
Migrates the nodejs install in the container image used for tests to the new installation mechanism:
https://github.com/nodesource/distributions/blob/69a45587cd87bd8c700e40bb8a8160e0c28d71d8/README.md#installation-instructions-1
Fixes #
> Migrate to new nodes install steps

- .gitignore
- lab/cfn/eks-workshop-ide-cfn.yaml
- Correct cfn-lint errors and 
- Modify so that DiskSize Override work as expected
- Added Cloud9Subnet to override subnet
- Remove logic for partition resize as Cloud9 does it on reboot by default (added reboot)
Fixes #
> Update the eks-worshop-ide-cfn.yaml

- manifests/modules/aiml/inferentia/.workshop/terraform/addon.tf
- manifests/modules/aiml/inferentia/.workshop/terraform/addon_infrastructure.tf
- website/docs/aiml/inferentia/compile.md
- website/docs/aiml/inferentia/inference.md
- website/docs/aiml/inferentia/wrapup.md
Runs AIML lab better in automated tests by removing `-it` flags from exec commands and increasing some timeouts.
Also fixed the lab working in Workshop Studio infrastructure provisioning.
Fixes #
> Fixed AIML lab running in automated tests

- .github/PULL_REQUEST_TEMPLATE.md
> Clarify make test command in PR Template

- manifests/modules/security/secrets-manager/.workshop/cleanup.sh
- manifests/modules/security/secrets-manager/.workshop/terraform/addon.tf
- manifests/modules/security/secrets-manager/external-secrets/external-secret.yaml
- manifests/modules/security/secrets-manager/external-secrets/kustomization.yaml
- manifests/modules/security/secrets-manager/mounting-secrets/kustomization.yaml
- manifests/modules/security/secrets-manager/mounting-secrets/serviceaccount.yaml
- manifests/modules/security/secrets-manager/secret-provider-class.yaml
- website/docs/security/secrets-management/_category_.json
- website/docs/security/secrets-management/secrets-manager/ascp.md
- website/docs/security/secrets-management/secrets-manager/create-secret.md
- website/docs/security/secrets-management/secrets-manager/external-secrets.md
- website/docs/security/secrets-management/secrets-manager/mounting-secrets.md
Added a cleanup script for the Secrets Manager lab, fixed some issues that prevented repeat testing and some language corrections
Fixes #
> Fix some secrets manager issues

- lab/bin/reset-environment
> fix reset-environment script env PWD single quote

- manifests/modules/automation/gitops/flux/.workshop/terraform/addon.tf
- manifests/modules/automation/gitops/flux/ci-ingress/ingress.yaml
- manifests/modules/automation/gitops/flux/ci-ingress/kustomization.yaml
- website/docs/automation/gitops/flux/ci.md
- website/docs/automation/gitops/flux/codecommit.md
- website/docs/automation/gitops/flux/deploy_application.md
Several updates to Flux CI content:
- Added some fixes for test reliability
- Removed dependency on ALB lab manifests
- Tweaked some writing style and added some context statements
Fixes #
> chore: Fix Flux CI tests, tweaked some language and explanations

- website/docs/security/secrets-management/secrets-manager/index.md
just a typo correction
just a typo correction
Fixes #
> Update index.md typo

- website/docs/autoscaling/compute/karpenter/further.md
- website/src/components/LaunchButton/index.tsx
- website/src/components/LaunchButton/styles.module.css
- website/src/theme/MDXComponents.js
Adds a link to the Karpenter workshop in the Karpenter lab
Fixes #
> update: Added link to Karpenter Workshop

- cluster/eksctl/cluster.yaml
- cluster/terraform/variables.tf
- docs/eks_version_upgrades.md
- hack/lib/kubectl-version.sh
- hack/upgrade-k8s.sh
- lab/scripts/installer.sh
- lab/scripts/setup.sh
- website/docusaurus.config.js
> feat: Update to 1.29

- website/docs/security/guardduty/cleanup.md
Cleanup page should come last for GuardDuty
Fixes #
> fix: Fix Guardduty cleanup page order

- website/docs/introduction/setup/your-account/using-terraform.md
A few wording and punctuation corrections for the Terraform page.
- [x ] My content adheres to the style guidelines
> fix: Text fixes for terraform docs

- manifests/modules/fundamentals/storage/fsxn/.workshop/terraform/addon.tf
Updates install of FSxN CSI driver to support new EKS add-on 
Fixes #
> Update FSxN module to support new EKS addon for CSI driver

- website/docs/fundamentals/storage/efs/efs-csi-driver.md
> fixed code block for efs csi driver

- website/docs/automation/gitops/argocd/cluster_bootstrap.md
Previous link was unreachable.
Fixes #
Fixed the link.
> Update github link for Automation module ArgoCD subtask

- website/docs/automation/gitops/flux/index.md
Previous link pointed to networking addon.
Previous link could confuse users who tried to understand what is going on under the hood.
Fixes #
Link to terraform addon.tf
> Update terraform link for Automation module flux subtask

- website/docs/observability/open-source-metrics/accessing-grafana.md
Added  printf "/n" at end to output the credentials to a new lines.
Fixes #
> Update accessing-grafana.md (adding new lines to output)

- manifests/modules/automation/controlplanes/ack/.workshop/cleanup.sh
- manifests/modules/automation/controlplanes/ack/.workshop/terraform/main.tf
Fix missing ACK provider block, make cleanup script handle incomplete lab
Fixes #884 
> update: Fix ACK lab provisioning

- website/docs/fundamentals/storage/efs/deployments.md
Corrected a wrong reference
Fixes #
> update: Fix reference to StatefulSet in EFS lab

- website/docs/fundamentals/storage/fsx-for-netapp-ontap/index.md
Fixes duplication of naming in FSxN docs.
- [ X ] My content adheres to the style guidelines
- [ X ] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
> fix: Remove duplicate text in FSx ONTAP introduction

- manifests/modules/networking/securitygroups-for-pods/.workshop/terraform/preprovision/main.tf
PR #923 upgraded the Terraform RDS module to 6.5 and this PR makes changes to the Terraform to be compatible with the new variables.
Fixes #
> chore: Update RDS TF module to 6.5

- manifests/modules/autoscaling/compute/karpenter/nodepool/nodeclass.yaml
- manifests/modules/autoscaling/compute/karpenter/nodepool/nodepool.yaml
> fix: Revert change to Karpenter nodepool

- cluster/terraform/eks.tf
> fix: Add cluster admin when using Terraform

- cluster/terraform/vpc.tf
Fixes #
- [V] My content adheres to the style guidelines
- [V] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
> add internal elb tag to vpc private subnets

- .github/workflows/release.yaml
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
- website/src/css/custom.scss
Implements search and dynamically resizes the nav bar to make room for new modules.
> feat: Implement search (and dynamic nav bar resizing)

- README.md
lack of external attendance
Fixes #
> community calls canceled

- lab/bin/delete-all-if-crd-exists
- lab/iam/policies/labs2.yaml
- manifests/modules/aiml/chatbot/.workshop/cleanup.sh
- manifests/modules/aiml/chatbot/.workshop/terraform/main.tf
- manifests/modules/aiml/chatbot/.workshop/terraform/outputs.tf
- manifests/modules/aiml/chatbot/.workshop/terraform/vars.tf
- manifests/modules/aiml/chatbot/nodepool/nodepool-inf2.yaml
- manifests/modules/aiml/chatbot/nodepool/nodepool-x86.yaml
- manifests/modules/aiml/inferentia/.workshop/cleanup.sh
- website/docs/aiml/chatbot/gradio.md
- website/docs/aiml/chatbot/nodepool.md
Fix iam issues in AI/ML chatbot PR and update to Karpenter v1
> fix: Resolve IAM issues in AI/ML chatbot lab

- website/docs/fundamentals/exposing/ingress/adding-ingress.md
- website/docs/fundamentals/exposing/loadbalancer/adding-lb.md
Use the new component that helps break down YAML for load balancer and ingress labs.
Fixes #
> update: Better explain load balancer and ingress YAML

- docs/style_guide.md
- website/docs/fundamentals/cluster-upgrades/index.md
- website/src/css/custom.scss
- website/src/theme/DocSidebarItem/Category/index.js
- website/src/theme/DocSidebarItem/Link/index.js
Add link out to EKS Upgrades. Introduce new "Explore" badge with link-out button.
Fixes #
- [ X ] My content adheres to the style guidelines
- [ X ] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
> feat: EKS Upgrades link-out with new "Explore" badge

- website/docs/introduction/helm/index.md
This clarifies whether or not this lab covers the authoring of Helm charts for participants' workloads
Fixes #
> fix: Fix grammar to avoid confusion

- manifests/modules/security/kyverno/.workshop/terraform/main.tf
- website/docs/security/kyverno/baseline-pss.md
- website/docs/security/kyverno/creating-policy.md
- website/docs/security/kyverno/index.md
- website/docs/security/kyverno/reports.md
- website/docs/security/kyverno/restricting-images.md
Language improvements to the Kyverno lab.
Also removed the installation of the Kyverno reporter UI helm chart since it was not being used and the version used was no longer installing successfully.
N/A
> update: Various Kyverno language fixes

- .github/workflows/test-observability.yaml
ensuring PR #1113 is tested by automation
> fix: add chaos engineering to tests

- docs/authoring_content.md
- website/docs/security/secrets-management/secrets-manager/ascp.md
- website/docs/security/secrets-management/secrets-manager/create-secret.md
- website/docs/security/secrets-management/secrets-manager/external-secrets.md
- website/docs/security/secrets-management/secrets-manager/index.md
- website/docs/security/secrets-management/secrets-manager/mounting-secrets.md
Makes various language consistency improvements for the Secrets Manager lab.
N/A
> update: Various Secrets Manager language fixes

- website/docs/observability/resource-view/workloads-view/policy_view.md
typo correction: 
PodDistributionBudgets  -> PodDisruptiontionBudgets
Fixes #
> fix: Policy view spelling error

- website/docs/introduction/setup/index.md
> Update access-code for RIV

- manifests/modules/aiml/chatbot/.workshop/terraform/main.tf
- manifests/modules/automation/controlplanes/ack/.workshop/terraform/main.tf
- manifests/modules/automation/controlplanes/crossplane/.workshop/terraform/main.tf
- manifests/modules/automation/gitops/flux/.workshop/terraform/main.tf
- manifests/modules/autoscaling/compute/cluster-autoscaler/.workshop/terraform/main.tf
- manifests/modules/autoscaling/workloads/hpa/.workshop/terraform/main.tf
- manifests/modules/autoscaling/workloads/keda/.workshop/terraform/main.tf
- manifests/modules/exposing/ingress/.workshop/terraform/main.tf
- manifests/modules/exposing/load-balancer/.workshop/terraform/main.tf
- manifests/modules/networking/network-policies/.workshop/terraform/main.tf
- manifests/modules/networking/vpc-lattice/.workshop/terraform/main.tf
- manifests/modules/observability/container-insights/.workshop/terraform/main.tf
- manifests/modules/observability/kubecost/.workshop/terraform/main.tf
- manifests/modules/observability/oss-metrics/.workshop/terraform/main.tf
- manifests/modules/observability/resiliency/.workshop/terraform/main.tf
- manifests/modules/security/eks-pod-identity/.workshop/terraform/main.tf
- manifests/modules/security/irsa/.workshop/terraform/main.tf
Updating the ALB controller to v1.10 requires additional IAM permissions met by upgrading the blueprints addons module.
N/A
> chore: Update EKS blueprints addons TF module to v1.19

- lab/iam/policies/labs3.yaml
- manifests/modules/fundamentals/storage/s3/.workshop/cleanup.sh
- manifests/modules/fundamentals/storage/s3/.workshop/terraform/main.tf
Fixes the S3 Mountpoint prepare command by expanding the S3 operations allowing by the IDE IAM role. Removing the Terraform configuration attempting to modify the role.
Fixes #1222
> fix: Fix IAM role for S3 Mountpoint lab

- .github/workflows/pr.yaml
Explicitly installs Terraform in the precommit PR check.
N/A
> fix: Install Terraform in precommit check

- website/docs/autoscaling/compute/karpenter/configure.md
Make sure to login to ECR Public before Karpenter lab to avoid authentication issues
Fixes #1239 
> fix: Login to ECR Public in Karpenter lab

- devenv.nix
- website/docs/networking/vpc-lattice/configuring-routes.md
Better to use VPC Lattice domain from HTTPRoute annotation instead of status.
N/A
> fix: Update wait command in VPC Lattice lab

- website/docs/aiml/inferentia/compile.md
> fix: [docs] adding a comma for better readability

- hack/build-ide-cfn.sh
- lab/cfn/eks-workshop-vscode-cfn.yaml
> fix: Use StackName to be unique in account

- manifests/modules/fundamentals/storage/s3/deployment/s3pvclaim.yaml
- website/docs/fundamentals/storage/mountpoint-s3/30-persistent-object-storage-with-mountpoint-for-amazon-s3.md
S3 lab issue outside of us-west-2
Updated the s3pvclaim.yaml to read the region from env variable AWS_REGION and respective web changes
Fixes # [1382](https://github.com/aws-samples/eks-workshop-v2/issues/1382)
> fix: allow s3 lab to work outside of us-west-2

- website/src/components/HomepageBanner/index.js
> chore: Update homepage promo link

- website/docs/autoscaling/compute/cluster-autoscaler/overprovisioning/setting-up.md
docs: Added YAML explainer components to  [Compute](https://www.eksworkshop.com/docs/autoscaling/compute/) > [Cluster Autoscaler (CA)](https://www.eksworkshop.com/docs/autoscaling/compute/cluster-autoscaler/) > [Cluster Over-Provisioning](https://www.eksworkshop.com/docs/autoscaling/compute/cluster-autoscaler/overprovisioning/) > Setting up Over-Provisioning<br/>
Adding YAML explainers helps learners better understand the configurations being applied
Relaetd to #1392 
> update: YAML breakdown for Overprovisioning section

- website/docs/observability/open-source-metrics/adot.md
Make OpenTelemetry collector config easier to read
Fixes #
> fix: Make OpenTelemetry collector config easier to read

- website/docs/fundamentals/managed-node-groups/basics/affinity/index.md
Added explanations for both yaml files present in this below document:
[Managed Node Groups](https://www.eksworkshop.com/docs/fundamentals/managed-node-groups/) > [MNG basics](https://www.eksworkshop.com/docs/fundamentals/managed-node-groups/basics/) > Pod Affinity and Anti-Affinity
Adding YAML explainers helps learners better understand the configurations being applied
Related to https://github.com/aws-samples/eks-workshop-v2/issues/1391
> docs: Added YAML file explanations for 'Pod Affinity and Anti-Affinity' section

- manifests/.workshop/terraform/base.tf
> chore: Bump AWS TF provider

- Makefile
- docs/authoring_content.md
- hack/ide.sh
- hack/shell.sh
- lab/Dockerfile
- lab/cfn/eks-workshop-vscode-cfn.yaml
- lab/scripts/code-server.sh
- lab/scripts/entrypoint.sh
- lab/scripts/setup.sh
Currently local development testing is limited to `make shell`, which only lets a contributor easily simulate the shell part of the user experience. As we rely on more features of VSCode this will become increasingly restrictive.
This PR adds the `make ide` command which provides the ability to run an instance of code-server in a local container which can be accessed in the browser. This allows contributors to test in an environment closer to the end-user experience.
```text
$ make ide
[...]
Installing extensions...
Installing extension 'redhat.vscode-yaml'...
Extension 'redhat.vscode-yaml' v1.18.0 was successfully installed.
Installing extensions...
Installing extension 'ms-kubernetes-tools.vscode-kubernetes-tools'...
Extension 'ms-kubernetes-tools.vscode-kubernetes-tools' v1.3.25 was …
```
> chore: Added local IDE for testing

- website/docs/security/secrets-management/secrets-manager/ascp.md
- website/docs/security/secrets-management/secrets-manager/create-secret.md
- website/docs/security/secrets-management/secrets-manager/external-secrets.md
- website/docs/security/secrets-management/secrets-manager/index.md
- website/docs/security/secrets-management/secrets-manager/mounting-secrets.md
> update: Various language fixes for Secrets Manager lab

- cluster/eksctl/cluster.yaml
- website/docs/introduction/setup/aws-event.md
- website/docs/introduction/setup/index.md
- website/docs/introduction/setup/your-account/cleanup.md
- website/docs/introduction/setup/your-account/index.md
- website/docs/introduction/setup/your-account/using-eksctl.md
- website/docs/introduction/setup/your-account/using-terraform.md
- website/src/remark/include-yaml.js
Fixes some typos and inconsistent language in the "In your account" pages.
Fixes #
> update: Various fixes to account setup procedure

- website/docs/fundamentals/exposing/ingress/multiple-ingress.md
- website/docs/fundamentals/exposing/loadbalancer/index.md
- website/docs/fundamentals/storage/ebs/statefulset-with-ebs.md
Add YAML file explanations: Fundamentals Section including Exposing Applications, and Storage
[Fixes #1389](https://github.com/aws-samples/eks-workshop-v2/issues/1389)
> update: Better explain YAML files for Exposing applications labs #1389

- website/docs/security/cluster-access-management/kubernetes-rbac.md
- website/docs/security/guardduty/log-monitoring/privileged_container_mount.md
- website/docs/security/kyverno/baseline-pss.md
- website/docs/security/kyverno/creating-policy.md
- website/docs/security/kyverno/restricting-images.md
- website/docs/security/secrets-management/secrets-manager/ascp.md
- website/docs/security/secrets-management/secrets-manager/external-secrets.md
Add YAML file explanations: Security Labs #1394
Fixes # https://github.com/aws-samples/eks-workshop-v2/issues/1394
> update: YAML file explanations: Security Labs #1394

- website/docs/observability/open-source-metrics/adot.md
Add YAML file explanations: Observability labs #1393
Fixes # https://github.com/aws-samples/eks-workshop-v2/issues/1393
> update: YAML file explanations for Observability Labs

- manifests/modules/introduction/helm/.workshop/cleanup.sh
- manifests/modules/introduction/helm/.workshop/terraform/outputs.tf
- manifests/modules/introduction/helm/.workshop/terraform/vars.tf
- manifests/modules/introduction/helm/values.yaml
- website/docs/introduction/helm/index.md
- website/docs/introduction/helm/tests/hook-install.sh
- website/docs/introduction/helm/tests/hook-replicas.sh
Migrates the Helm lab to use the chart for the UI component of the sample app instead of NGINX. This is driven by:
1. Following pattern of the rest of the workshop by using the sample app
2. Mitigating Bitnami dependency
Fixes #1590
> update: Migrated Helm lab to sample app chart

- website/docs/troubleshooting/dns/4-check-vpc.md
Improved messaging in the Conclusion section
Improved messaging in the Conclusion section
Fixes #
- [x ] My content adheres to the style guidelines
- [ x] The PR has meaningful title and description of the changes that will be included in the workshop release notes
> update: Updated messaging in the troubleshooting DNS conclusion

- website/docs/troubleshooting/workernodes/three.md
Added the command to export the NODE_NAME variable, this is to workaround scenarios where the original node crashed, making the original NODE_NAME export invalid
Added the command to export the NODE_NAME variable, this is to workaround scenarios where the original node crashed, making the original NODE_NAME export invalid
Fixes #
- [x ] The PR has meaningful title and description of the changes that will be included in the workshop release notes
> fix: Added the command to export the NODE_NAME variable

- manifests/modules/aiml/q-cli/setup/eks-mcp.json
- website/docs/aiml/q-cli/basic-troubleshooting.md
- yarn.lock
Updated EKS MCP server version to 0.1.13
Added command to clean up failing Pod from the basic troubleshooting lab
Fixes #
- [X ] My content adheres to the style guidelines
- [ X] The PR has meaningful title and description of the changes that will be included in the workshop release notes
> update: EKS MCP server version change

- manifests/modules/autoscaling/compute/cluster-autoscaler/deployment.yaml
- manifests/modules/autoscaling/compute/overprovisioning/scale/deployment.yaml
- website/docs/fundamentals/compute/managed-node-groups/cluster-autoscaler/overprovisioning/scaling.md
> fix: Fix replicas needed for over-provisioning

- package.json
- website/netlify-build.sh
- yarn.lock
> chore: Make sure netlify build uses yarn immutable
