aws-samples/eks-workshop-v2

environment/installer.sh
terraform/ide.tf
terraform/modules/cluster/codecommit.tf
terraform/modules/cluster/efs.tf
terraform/modules/ide/cloud9.tf
terraform/modules/ide/scripts/bootstrap.sh

This PR updates the bootstrap process for the Cloud9 instance so that it can run idempotently. This is done by:
1. Changing where the filesystem resize marker file is placed
2. Using the AWS CLI install update flag
3. Removing the CodeCommit SSH key before writing it
There is also a change to add triggers to the invocation Lambda whenever the bootstrap scripts change or a new Cloud9 instance is created.
Fixes #

fix: Cloud9 bootstrap process should run idempotently

---

governance/steering.md

Nominate [Christina Andonov](https://github.com/candonov) as maintainer for Automation WG
Christina Andonov has a wealth of experience and expertise in SRE and DevOps practices. Her current role at AWS focus on driving our DevOps and GitOps PoV in AppMod.
She is an open source maintainer for [Blueprints for Crossplane on Amazon EKS](https://github.com/awslabs/crossplane-on-eks) and [EKS Blueprints for Terraform](https://github.com/aws-ia/terraform-aws-eks-blueprints) projects
Requesting the [steering committee](https://github.com/aws-samples/eks-workshop-v2/blob/main/governance/steering.md) to review and [vote](https://github.com/aws-samples/eks-workshop-v2/blob/main/governance/model.md#steering-committee) on the nomination.

Nominate Christina Andonov as maintainer for Automation WG

---

governance/steering.md

Nominate [Steven David](https://github.com/StevenDavid) as Maintainer for Observability WG. 
Steven supported the creation of the current observability modules, collaborating with working group members to raise the bar on content and supporting the workshop events at reinvent 2022.  
Requesting the [steering committee](https://github.com/aws-samples/eks-workshop-v2/blob/main/governance/steering.md) to review and [vote](https://github.com/aws-samples/eks-workshop-v2/blob/main/governance/model.md#steering-committee) on the nomination.

adding observability maintainer

---

governance/steering.md

Nominate [Rodrigo Bersa](https://github.com/rodrigobersa) as Maintainer for Security WG.
Rodrigo will lead the Security Domain for AppMod.
Requesting the [steering committee](https://github.com/aws-samples/eks-workshop-v2/blob/main/governance/steering.md) to review and [vote](https://github.com/aws-samples/eks-workshop-v2/blob/main/governance/model.md#steering-committee) on the nomination.

adding security maintainer

---

environment/workspace/modules/autoscaling/compute/overprovisioning/setup/deployment-pause.yaml
environment/workspace/modules/autoscaling/workloads/cpa/deployment.yaml
environment/workspace/modules/networking/prefix/deployment-pause.yaml

Updated k8s.gcr.io Container registry references to registry.k8s.io as per https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
N/A

Updated k8s.gcr.io references to registry.k8s.io

---

website/docs/security/guardduty/findings/anonymous-user/finding-3.2.md

Users will not be able to push through with the creation of a pod that will trigger the GuardDuty `Impact:Kubernetes/SuccessfulAnonymousAccess` finding because of errors with the variables in the commands. See [this section](https://www.eksworkshop.com/docs/security/guardduty/findings/anonymous-user/finding-3.2).
Fixes variable naming and variable usage

Fix issues with variables in GuardDuty module

---

website/docs/fundamentals/exposing/loadbalancer/adding-lb.md

So users partaking in the workshop can properly view the NLB created during the [Adding LB](https://www.eksworkshop.com/docs/fundamentals/exposing/loadbalancer/adding-lb/) portion
Fixes the AWS Console link's filter with an incorrect tag

Fix tag filter for AWS Console link

---

environment/workspace/modules/security/sealed-secrets/deployment.yaml

Fixes the Deployment patch in the sealed secrets chapter so that it only references to values stored in the secret, not values that were moved to a ConfigMap.
Fixes #332 

fix: Update sealed secrets deployment to only reference secrets entries

---

website/docs/fundamentals/storage/efs/deployments.md

…as it doesn't give the correct/expected output
Fixes #

removed 'deployment/assets' from the kubectl exec command on line 79 as it gives wrong output

---

test/util/src/lib/gatherer/gatherer.ts
test/util/src/lib/markdownsh.ts
test/util/src/lib/shell/shell.ts
test/util/test-content/basics/empty.md
test/util/tests/fixtures/basic/a.md
test/util/tests/fixtures/basic/b.md
test/util/tests/fixtures/basic/empty/block.md
test/util/tests/fixtures/basic/nested/index.md
test/util/tests/gatherer.test.ts

The test utility currently identifies bash blocks with no commands as having a command thats an empty string, which causes a timeout. This PR ignores these empty blocks when gathering the commands and also includes an additional safeguard to reject empty commands sent to the shell processor.
Fixes #

fix: Test utility should properly handle blocks with no commands

---

.github/workflows/ci.yaml
.github/workflows/e2e-dispatch.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/test-cleanup.yaml
terraform/main.tf
terraform/modules/cluster/providers.tf
terraform/modules/ide/main.tf
test/terraform/main.tf

Terraform version 1.4 has been released and we currently pin to 1.3.X. This PR relaxes this restriction and upgrades the TF version in all testing workflows.
Fixes #

chore: Support for TF 1.4

---

docs/faq.md

Explain how to bypass issues with helm chart using expired credentials for public ECR.
Fixes #

Add helm logout for ECR Public helm chart issues (kubecost, karpenter..)

---

terraform/modules/cluster/addons.tf

A blueprints addon is causing terraform init to fail, this change removes that module.
Fixes #

fix: Remove problematic blueprints addon

---

governance/steering.md

Adding Sébastien Allamand as a maintainer for Automation module, Sébastien has contributed to the workshop in many forms from running live workshops, testing, and reviewing PRs.

Add Sébastien Allamand as maintainer for Automation

---

governance/steering.md

Umair Ishaq has extensive knowledge of Kubernetes networking and how CNI operates. Umair has been the primary contributor to the current networking chapter and the necessary infrastructure modifications.
Seeking the evaluation and vote of the nomination by the steering committee.

Nominate Umair Ishaq as maintainer for Networking WG

---

website/docs/fundamentals/fargate/sizing.md

Update Fargate CPU/Memory link to use EKS doc: https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html#fargate-cpu-and-memory
Was pointing to ECS Fargate docs.
Fixes #

Update Fargate CPU/Memory link to use EKS doc

---

website/docs/introduction/kustomize/index.md

The kustomize patch updates spec/replicas to 3 replicas. 
apiVersion: apps/v1
kind: Deployment
metadata:
name: checkout
spec:
replicas: 3
Fixes #

Fix number of replicas field 

---

website/docs/fundamentals/managed-node-groups/affinity/index.md

In the previous 'Add nodes' section the number of nodes in the managed-ondemand node group was increased from 2 to 3. Events for pending pod: "1 node(s) didn't match pod affinity rules...that the pod didn't tolerate, 2 node(s) didn't match pod anti-affinity rules."
So maybe should read something like the following to consider the pod affinity rule as well: 
If we check the running pods we can see that the third checkout pod has been placed in a Pending state since two of the nodes already have a pod deployed and the third node does not have a checkout-redis pod running.
Fixes #

Update statement regarding 3rd checkout replica

---

website/docs/networking/prefix/index.md
website/docs/networking/security-groups-for-pods/index.md

Improve UX by having user start with Prefix Delegation to understand VPC CNI before moving to other sections.

Move order of Networking modules to prioritize prefix delegation

---

website/Brewfile.netlify
website/netlify-build.sh

Currently the Netlify homebrew integration is used to install kubectl. However, this doesn't let us pin the kubectl to a known compatible version and this has caused issues with the default version moving to 1.27.
This PR pins the version of kubectl by installing the binary directly in the wrapper build script.
Fixes #

chore: Pin kubectl version used in netlify

---

terraform/modules/cluster/variables.tf

We've had several reports of incidents of nodes failing to become healthy with errors like:
```
PLEG is not healthy: pleg was last seen active 41m35.274123984s ago
```
It may be related to this issue since we are using that AMI: https://github.com/awslabs/amazon-eks-ami/issues/1071
This PR bumps the AMI.
Fixes #

fix: Bump AMI version to 1.23.15

---

website/docs/introduction/ide.md

Fixes tip and link in ide.md file

---

website/docs/introduction/getting-started/first.md

Adding additional verbiage to provide details of how to use the '-f' option with "kubectl logs" to "follow" the output.
This PR does not address an issue - it is an "enhancement"
Fixes #

Adding verbiage about -f --follow option for logs output

---

website/docs/fundamentals/managed-node-groups/index.md

The command originally identified did not provide the output as it had been explained.  Since the output (which shows the Availability Zones) is useful, I updated the doc with an example that would provide that output.

Update commands and expected return values

---

website/docs/networking/custom-networking/vpc.md

Correcting the wrong private subnets value on this [content](https://github.com/aws-samples/eks-workshop-v2/blob/main/website/docs/networking/custom-networking/vpc.md).
Fixes #

Correct the wrong private subnets value

---

terraform/modules/cluster/rds.tf

Upgrades the version of the RDS database created by the Terraform to 8.0.32
Fixes #498 

fix: Upgrade RDS version to 8.0.32

---

website/docs/security/guardduty/findings/finding7.md

The file path to delete the privileged pod example was wrong.
Fixes #

Corrected a wrong file path

---

terraform/iam.tf

Deployment of this terraform stack in my local AWS environment failed and claimed malformed json. An IAM role if a Sid is declared, requires a non-empty Sid. If a more descriptive name is better, feel free to use something else :)
What this PR does / why we need it:
This PR addresses an incorrect IAM policy in iam.tf. A policy requires a non-empty Sid. Once added, terraform successfully spins up the EKS environment.
Which issue(s) this PR fixes:
493: Malformed json in iam.tf
Fixes #
Quality checks
[ x] My content adheres to the style guidelines
[x ] I ran make test or make e2e-test and it was successful - I ran terraform fmt and deployed to local environment with the fix.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

Update iam.tf to address malformed json policy

---

terraform/modules/cluster/addons.tf
terraform/modules/cluster/codecommit.tf
terraform/modules/cluster/efs.tf

EFS has changed the permission model such that the CSI driver requires the `elasticfilesystem:TagResource` IAM permission.
Fixes #

fix: Add EFS tag resource IAM permission to CSI driver

---

website/docs/autoscaling/compute/karpenter/consolidation.md

One of the advantages of Karpenter is its ability to replace nodes with cheaper variants when it makes sense to. Added simple demonstration by scaling the replica to 1 and observe Karpenter replace the m5.large with the cheaper lower speced c5.large.
Fixes #

Demonstrate the consolidation replace mechansim

---

terraform/main.tf

There are modules leveraged in the Terraform which are not compatible with AWS Terraform Provider >= 5.0 Constraint the version of the provider until these are upgraded.
Fixes #

fix: Limit Terraform AWS provider to < 5.0

---

website/docs/networking/vpc-lattice/setup.md

Creation of policy points to the wrong location
file://eks-workshop/manifests/modules/networking/vpc-lattice/controller/recommended-inline-policy.json
It should be 
file://eks-workshop/modules/networking/vpc-lattice/controller/recommended-inline-policy.json
This PR fixes an issue with a command that includes the wrong path to a policy file. 
Fixes #
- [ x] My content adheres to the style guidelines
- [ x ] I ran `make test` or `make e2e-test` and it was successful

Update setup.md in website/vpc-lattice

---

website/docs/fundamentals/storage/ebs/statefulset-with-ebs.md

Current rollout command is  
`kubectl rollout status --timeout=60s statefulset/catalog-mysql-ebs -n catalog`
which will lead to `error: timed out waiting for the condition`. Increase timeout can resolve this issue.
Fixes #

Change timeout to 100s in chapter "StatefulSet with EBS Volume"

---

manifests/modules/automation/controlplanes/ack/.workshop/terraform/addon.tf
manifests/modules/automation/controlplanes/crossplane/.workshop/terraform/addon.tf
manifests/modules/exposing/ingress/.workshop/terraform/addon.tf
manifests/modules/exposing/load-balancer/.workshop/terraform/addon.tf
manifests/modules/observability/kubecost/.workshop/terraform/addon.tf
manifests/modules/observability/oss-metrics/.workshop/terraform/addon.tf
manifests/modules/security/irsa/.workshop/terraform/addon.tf

There is an intermittent issue where an lab installs the AWS LB controller in Terraform then immediately attempts to create a load balancer via manifests. This appears to be a race condition due to the helm chart not completing installation.
This PR adds configuration to the LB controller helm chart installs so that it will wait for the chart to install.
Fixes #629 

Wait for AWS LB controller helm release to install

---

manifests/modules/fundamentals/fargate/.workshop/cleanup.sh
manifests/modules/fundamentals/fargate/.workshop/terraform/addon.tf
manifests/modules/fundamentals/fargate/profile/fargate.yaml
website/docs/fundamentals/fargate/enabling.md
website/docs/fundamentals/fargate/index.md
website/docs/fundamentals/fargate/scheduling.md
website/docs/fundamentals/fargate/tests/hook-enabling.sh
website/docs/fundamentals/fargate/tests/hook-suite.sh

Historically the Fargate profile has been created by Terraform. However this causes the prepare environment phase to take longer without user feedback and hides details from the user. This PR changes it so the user creates the Fargate profile themselves.
Fixes #

User now creates Fargate profile

---

manifests/modules/fundamentals/mng/.workshop/cleanup.sh
manifests/modules/fundamentals/mng/.workshop/terraform/addon.tf
manifests/modules/fundamentals/mng/taints/nodegroup.yaml
website/docs/fundamentals/managed-node-groups/index.md
website/docs/fundamentals/managed-node-groups/taints/configuring-taints.md
website/docs/fundamentals/managed-node-groups/taints/implementing-tolerations.md
website/docs/fundamentals/managed-node-groups/taints/tests/hook-configure-taints.sh
website/docs/fundamentals/managed-node-groups/taints/tests/hook-pending-pod.sh

Currently the node group for applying taints is provisioned with Terraform. This seems to cause confusion in such an early module as provisioning it this way can take several minutes and is quite variable.
This PR changes this so that the node group is manually provisioned by the user. This makes the process more transparent to the user.
Fixes #

Change how tainted node group is created.

---

manifests/modules/observability/kubecost/.workshop/terraform/addon.tf
manifests/modules/observability/kubecost/.workshop/terraform/values.yaml
website/docs/observability/kubecost/costallocation.md
website/docs/observability/kubecost/introduction.md
website/docs/observability/kubecost/tests/hook-kubecost-deployment.sh

Ensures the kubecost LB is external-facing and added test to validate this.
Fixes #635 

Ensure kubecost LB is external

---

website/docs/introduction/setup/your-account/using-eksctl.md

The step found in: Setup | In your AWS account | Using eksctl
could use some additional clarity as to not imply that the reader should delete their cluster as the next section the same page might have indicated.
No issue - this is a doc cleanup recommendation
Fixes #

Update Page Layout and add Tips about Clean Up

---

manifests/modules/exposing/ingress/multiple-ingress/ingress-catalog.yaml

By default this configuration will make the Target Group for the catalog application unhealthy, although the [ALB documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html) specifies that the traffic will be send if all the targets are unhealthy I think is a better approach to have everything healthy. 
Fixes #

Adding Health Check to catalogue ingress

---

manifests/modules/automation/controlplanes/crossplane/application/kustomization.yaml

It fixes the broken link in `kustomization.yaml` file in `crossplane/application` module.
Fixes #

Fix broken linkg in crossplane module

---

lab/scripts/installer.sh

Running the `awscurl` command in the OSS metrics section gives this error:
```
ValueError: No access key is available
```
Pinning awscurl to version 0.28 resolves this error but gives:
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
```
Pinning urllib3 to 1.26.6 resolves this error.
This can be manually resolved with the following command:
```
pip3 install -q awscurl==0.28 urllib3==1.26.6
```
Fixes #

Pin awscurl and urllib3 versions

---

website/docs/fundamentals/exposing/index.md
website/docs/fundamentals/fargate/index.md
website/docs/fundamentals/managed-node-groups/index.md
website/docs/fundamentals/storage/index.md

This PR reorders the labs in the Fundamentals section so that it starts with labs that are more development focused. The LB and storage labs are quicker to execute and provide a more immediate accomplishment. There is also commonly a first question after Getting Started about accessing the sample application, which is now the next lab.
Fixes #

update: Reorder labs in Fundamentals section

---

test/util/README.md
test/util/src/lib/markdownsh.ts
test/util/src/lib/shell/shell.ts

The PR provides an environment variable called `TEST_OUTPUT` to test hooks so that they can easily perform assertions on the output of the script in the `bash` block. It also adds corresponding documentation to the test util.
Fixes #

Pass test output to test hooks

---

website/docs/introduction/setup/your-account/using-terraform.md

The Terraform page's example command for cleaning up did not include the `destroy` verb. Without it Terraform proceeds to destroy exactly nothing.
It corrects the workshop tutorial
I did not raise an issue for this one

Fix the terraform destroy command

---

test/util/package-lock.json
test/util/package.json
test/util/src/lib/gatherer/gatherer.ts

Remark 15.0 and its related dependencies introduced some breaking changes which needs an update of multiple libraries at once.
Fixes #

chore: Upgrade remark to v15 and associated dependencies

---

website/docs/aiml/inferentia/compile.md

Fixes a time out issue during the AI/ML module test.
Time out issue during the model creation section in AIML Compile a pre-trained model for AWS Inferentia.
Fixes #
https://github.com/aws-samples/eks-workshop-v2/actions/runs/6716768282/job/18253501394#step:8:34

Fixing time out issue during test

---

manifests/modules/fundamentals/storage/ebs/.workshop/cleanup.sh
manifests/modules/fundamentals/storage/ebs/.workshop/terraform/addon.tf
website/docs/fundamentals/storage/ebs/ebs-csi-driver.md
website/docs/fundamentals/storage/ebs/index.md

User installs EBS CSI addon instead of it happening in Terraform
Fixes #

update: User installs EBS CSI addon

---

lab/cfn/eks-workshop-ide-cfn.yaml

Fix for loop when instance isn't running yet

---

website/docs/security/pod-security-standards/index.md

Removing additional start symbol which seems like a typo for bold text.

fix: Formating in Pod Security Standards introduction

---

lab/scripts/installer.sh
manifests/modules/observability/logging/cluster/.workshop/cleanup.sh

chore: Fixed cleanup of control plane logging lab

---

.github/workflows/website-build.yaml
hack/lib/kubectl-version.sh
website/netlify-build.sh

Makes updating the version of kubectl in multiple places slightly easier.
Fixes #

chore: Source kubectl version from shared script

---

lab/cfn/eks-workshop-ide-cfn.yaml

Update Lambda runtime for Cloud9 customization. To be honest, I guessed 3.9 deprecated soon, but it's not, it's 3.8 :)
Nevermind, I've executed the creation of the ide environment and it works without any code modification.
Fixes #

chore: Update Lambda runtime for Cloud9 CloudFormation

---

lab/bin/reset-environment
lab/cfn/eks-workshop-ide-cfn.yaml
lab/scripts/setup.sh

This PR adds the ability to enable analytics on labs run by participants. This feature is not enabled by default and not used when running the workshop in your own AWS account. It is intended only for when the workshop is run at AWS events in accounts provided by AWS.
Fixes #

feat: Analytics for AWS events

---

manifests/modules/networking/vpc-lattice/.workshop/cleanup.sh
manifests/modules/observability/container-insights/.workshop/terraform/addon.tf
manifests/modules/observability/oss-metrics/.workshop/terraform/addon.tf
website/docs/autoscaling/compute/karpenter/node-provisioning.md

- Fix ADOT Version so it's support 1.29
- Fix VPC Lattice cleanup to delete CRD after the resources
- Move the karpenter wait hook on the rollout command
Fixes #

[FIX] Update ADOT version, fix VPC Lattice module cleanup, karpenter test

---

manifests/modules/fundamentals/mng/graviton/.workshop/cleanup.sh
manifests/modules/fundamentals/mng/graviton/.workshop/terraform/addon.tf
website/docs/fundamentals/managed-node-groups/graviton/configuring-graviton.md

Using `eksctl` to create the node group for Graviton nodes doesn't provide much value and another potential source of issues (see #802). This PR changes that step to use the `aws` CLI directly, which is also in line with the Spot lab.
Fixes #

update: Use AWS CLI for Graviton nodes instead of eksctl

---

cluster/terraform/eks.tf

Changes to be committed:
modified:   cluster/terraform/eks.tf
In the eks-workshop, Network section, Network Policies topic and title Debugging. The doc explains that it is possible to see the Network Policy logs via Network Policy agent. But by default the flag: enablePolicyEventLogs is set as "false".
To enable the logs, the workshop needs to pass this flag to the vpc-cni addon in the beggining of the environment setup.
I don't now about the eksctl implementation if this flags needs to be added, but at least in terraform it needs.
It will make the doc coherent for the new people that is starting to learn about EKS 
Fixes #
Add the flag enablePolicyEventLogs as true in cluster/terraform/eks.tf
I didn't run any make tests because it was taking too much time and my credentials were expiring …

fix: Enable policy event logs for Pod Identity agent

---

website/docs/networking/vpc-cni/prefix/index.md

Fix a broken link to prefix mode
NA

Fix a broken link to prefix mode

---

manifests/modules/autoscaling/compute/karpenter/.workshop/terraform/main.tf

Update karpenter to latest since we were using a version not officially supported on 1.29.
Fixes #849 

Update karpenter to 0.35.4 and bump eks_blueprints_addons to 1.16.0

---

website/docs/fundamentals/managed-node-groups/spot/instance-diversification.md

Corrected a couple of typos
Fixes #

update: Fix typos in Spot instance diversification description

---

website/docs/autoscaling/compute/cluster-autoscaler/test-ca.md

Changed the namespace filter to all
Fixes #

update: Watch all pods during cluster autoscaler scale out

---

cluster/eksctl/cluster.yaml

Just to be aligned with default version in the EKS console.
Didn't manage to find this information in https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html
Terraform cluster creation use (with `most_recent` flag) so `1.18.0` as of today (see https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/aws-vpc-cni-network-policy/main.tf#L125)
Is there interesting to always use last version?
Something like:
```
aws eks describe-addon-versions --addon vpc-cni --query "addons[].addonVersions[0].addonVersion" --output text | sed "s/v\(.*\)-eksbuild.*/\\1/"
```
Might help to generate the cluster.yaml with the latest version.
None
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Update vpc-cni to default version 1.16.0 in eksctl instructions creation

---

website/docs/autoscaling/compute/cluster-autoscaler/overprovisioning/how-it-works.md

update: Fix typo in cluster autoscaler over-provisioning seciton

---

website/docs/automation/gitops/flux/ci.md
website/docs/automation/gitops/flux/cluster_bootstrap.md

Updating the flux CLI to 2.2.3 caused an error to start appearing in the CI section:
```
this cluster has already been bootstrapped with Flux v2.2.3! Please use 'flux bootstrap' to upgrade
```
This PR slightly restructures the content so all the extra components are installed during initial `flux bootstrap` rather than using a follow-up `flux install`.
Fixes #

update: Update flux module for 2.2.3

---

website/docs/autoscaling/compute/cluster-autoscaler/overprovisioning/setting-up.md

update: Fix test explaining resources in cluster over-provisioning section

---

website/docs/introduction/setup/your-account/using-terraform.md

export EKS_CLUSTER_NAME
Add the required step to define EKS_CLUSTER_NAME.
Missing variable definition for EKS_CLUSTER_NAME.
Fixes #

fix: Set EKS cluster name in Terraform self-service instructions

---

manifests/modules/networking/vpc-lattice/.workshop/cleanup.sh
website/docs/networking/vpc-lattice/setup.md

Upgrades the VPC Lattice controller to version 1.0.5
Also improves the lab cleanup script by waiting longer for the target groups to be deleted and properly waiting for the VPC association to be deleted.
Fixes #

update: Upgraded VPC Lattice controller to 1.0.5

---

website/docs/security/pod-security-standards/restricted.md

Just removing a single extra space from a command. Not critical by any means. Just helping to make it look nicer.
Fixes #

Remove extra space from command

---

manifests/base-application/catalog/statefulset-mysql.yaml
manifests/base-application/orders/deployment-mysql.yaml
manifests/modules/fundamentals/storage/ebs/statefulset-mysql.yaml
website/docs/fundamentals/storage/ebs/statefulset.md

The Security Group for Pods module provision a [RDS MySQL 8.0 instance](https://github.com/aws-samples/eks-workshop-v2/blob/main/manifests/modules/networking/securitygroups-for-pods/.workshop/terraform/preprovision/main.tf#L30) for the catalog microservice.
The statefulset still use a [5.7 version](https://github.com/aws-samples/eks-workshop-v2/blob/main/manifests/base-application/catalog/statefulset-mysql.yaml#L27) and the data model & the catalog application is compatible but it's probably better to have them in sync to avoid future problems and unnecessary participants questions about this drift.
The [`ignore-db-dir` is deprecated starting version 8](https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html).
Also change the version for the orders microservice, without any …

Update MySQL statefulset & deployments to 8.0

---

manifests/modules/autoscaling/compute/karpenter/.workshop/cleanup.sh
manifests/modules/autoscaling/compute/karpenter/.workshop/terraform/main.tf
manifests/modules/autoscaling/compute/karpenter/.workshop/terraform/outputs.tf
manifests/modules/autoscaling/compute/karpenter/.workshop/terraform/vars.tf
manifests/modules/autoscaling/compute/karpenter/nodepool/nodepool.yaml
renovate.json
website/docs/autoscaling/compute/karpenter/configure.md
website/docs/autoscaling/compute/karpenter/index.md

This PR changes the Karpenter lab so its installed with a helm chart by the user instead of in the Terraform. This makes it more transparent to the user what is happening.
The Terraform is still used to create the various IAM roles, SQS queue and cluster access entries.
Related to #863 

update: Changed Karpenter lab to install via helm chart

---

manifests/modules/autoscaling/compute/cluster-autoscaler/.workshop/cleanup.sh
manifests/modules/autoscaling/compute/cluster-autoscaler/.workshop/terraform/main.tf
manifests/modules/autoscaling/compute/cluster-autoscaler/.workshop/terraform/outputs.tf
manifests/modules/autoscaling/compute/cluster-autoscaler/.workshop/terraform/vars.tf
website/docs/autoscaling/compute/cluster-autoscaler/index.md
website/docs/autoscaling/compute/cluster-autoscaler/install.md
website/docs/autoscaling/compute/cluster-autoscaler/test-ca.md

This PR changes the Cluster Autoscaler lab so its installed with a helm chart by the user instead of in the Terraform. This makes it more transparent to the user what is happening.
The Terraform is still used to create the IAM role, IRSA entries used by Cluster Autoscaler.
Related to #863 

update: Changed Cluster Autoscaler lab to install via helm chart

---

manifests/modules/automation/gitops/argocd/.workshop/cleanup.sh
manifests/modules/automation/gitops/argocd/.workshop/terraform/main.tf
manifests/modules/automation/gitops/argocd/.workshop/terraform/outputs.tf
manifests/modules/automation/gitops/argocd/.workshop/terraform/vars.tf
manifests/modules/automation/gitops/argocd/values.yaml
renovate.json
website/docs/automation/gitops/argocd/access_argocd.md

This PR changes the ArgoCD lab so its installed with a helm chart rather than the manifests that are currently used. This makes it consistent with other labs where we use helm charts and allows us to track any updates to ArgoCD with automation.
Fixes #

update: Changed ArgoCD lab to install via helm chart

---

manifests/modules/exposing/ingress/.workshop/cleanup.sh
manifests/modules/exposing/ingress/.workshop/terraform/main.tf
manifests/modules/exposing/ingress/.workshop/terraform/outputs.tf
manifests/modules/exposing/ingress/.workshop/terraform/vars.tf
manifests/modules/exposing/load-balancer/.workshop/cleanup.sh
manifests/modules/exposing/load-balancer/.workshop/terraform/main.tf
manifests/modules/exposing/load-balancer/.workshop/terraform/outputs.tf
manifests/modules/exposing/load-balancer/.workshop/terraform/vars.tf
website/docs/fundamentals/exposing/ingress/index.md
website/docs/fundamentals/exposing/ingress/introduction.md
website/docs/fundamentals/exposing/loadbalancer/index.md
website/docs/fundamentals/exposing/loadbalancer/introduction.md

This PR changes the Load Balancer and Ingress labs so the aws-load-balancer-controller is installed by the user with a helm chart rather than by the Terraform. This makes it consistent with other labs where we use helm charts and allows us to track any updates to the aws-load-balancer-controller with automation.
Related to #863 

update: Changed Load Balancer and Ingress labs to install LBC via helm chart

---

manifests/modules/introduction/helm/.workshop/cleanup.sh
manifests/modules/introduction/helm/.workshop/terraform/outputs.tf
manifests/modules/introduction/helm/.workshop/terraform/vars.tf
manifests/modules/introduction/helm/values.yaml
website/docs/introduction/helm/index.md
website/docs/introduction/helm/tests/hook-suite.sh
website/docs/introduction/kustomize/index.md

With multiple labs now directing the user to install helm charts manually we should cover Helm basics so its clear whats happening. This provides an equivalent to the Kustomize introduction lab but for 3rd party components instead of the sample application.
Related to #863 

new: Added lab on Helm

---

website/src/css/custom.scss

In dark mode the website lacked contrast for links and the highlight tones for the YAML annotations did not fit the Prism theme. This PR adjusts both of these.
N/A

fix: Improved contrast for links and yaml highlights in dark mode

---

manifests/modules/observability/oss-metrics/.workshop/terraform/main.tf
manifests/modules/observability/oss-metrics/.workshop/terraform/vars.tf
manifests/modules/observability/oss-metrics/adot/opentelemetrycollector.yaml

Migrating to EKS 1.30 was a priority to remain updated, but the ADOT addon does not currently support 1.30. Until this is the case this lab uses the upstream OpenTelemetry operator with the ADOT collector images.
N/A

update: Migrate OSS metrics lab to OpenTelemetry operator

---

website/docs/observability/resource-view/workloads-view/deployment_view.md

Name of the deployment is wrong. It is mentioned "orders" but it should be "carts"
Fixes #

update: Fix inconsistent deployment name in Resource View section

---

website/docs/observability/container-insights/collect-metrics-adot-ci.md
website/docs/observability/container-insights/visualize-application-metrics-cloudwatch.md

Corrects a typo introducing how the ADOT manifests are broken down.
Fixes #1046 

fix: Corrected typo in ADOT manifest breakdowns

---

lab/iam/policies/base.yaml

KMS IAM permissions provided to the IDE need to be expanded to account for the KMS alias pattern of the EKS Terraform module. This allows an EKS cluster to be created using Terraform route correctly.
Fixes #1091

fix: Allow appropriate IDE KMS permissions for Terraform cluster creation

---

manifests/modules/autoscaling/compute/karpenter/.workshop/terraform/outputs.tf
manifests/modules/autoscaling/compute/karpenter/.workshop/terraform/vars.tf
manifests/modules/autoscaling/compute/karpenter/nodepool/nodeclass.yaml
manifests/modules/autoscaling/compute/karpenter/nodepool/nodepool.yaml
website/docs/autoscaling/compute/karpenter/consolidation.md
website/docs/autoscaling/compute/karpenter/node-provisioning.md
website/docs/autoscaling/compute/karpenter/setup-provisioner.md

Upgrades the Karpenter lab to v1.
Fixes #

update: Upgrade Karpenter lab to v1

---

manifests/modules/networking/securitygroups-for-pods/.workshop/cleanup.sh

User reports and automated tests show instability in the SG for Pods lab cleanup script. This seems to be related to a wide variability in how long it takes the worker nodes to be replaced when they are terminated in cleanup.
This change removes the node termination and instead deletes the `catalog` namespace, which should clean up all modifications made during this lab.
Related to #1062 

fix: Resolve instability with SG for Pods lab cleanup

---

manifests/modules/networking/custom-networking/.workshop/cleanup.sh

Changed the sequence for custom networking cleanup with intention to improve reliability. Inconsistent failures happening seem to be related to time it takes to terminate and re-provision nodes.
Related to #1062 

fix: Improve reliability of custom networking cleanup

---

manifests/modules/networking/vpc-lattice/.workshop/terraform/main.tf
manifests/modules/security/eks-pod-identity/.workshop/terraform/main.tf
manifests/modules/security/irsa/.workshop/terraform/main.tf
website/docs/security/amazon-eks-pod-identity/verifying-dynamo.md
website/docs/security/iam-roles-for-service-accounts/verifying-dynamo.md

A type in the annotations for several load balancers was causing classic load balancers to be created instead of NLBs.
Also changed how the URLs for the load balancers are displayed so that browser doesn't try HTTPS automatically
N/A

fix: Make sure NLBs are provisioned

---

website/src/components/Terminal/index.tsx

Currently the button used to copy all the commands in a terminal window adds an extra empty line at the end, which is confusing when using the VSCode IDE. This PR removes any empty space before/after content copied from the terminal.
N/A

fix: No empty line at end of terminal copy

---

website/docs/introduction/navigating-labs.md
website/docs/introduction/setup/your-account/index.md

Removes documentation of the Cloud9 IDE option from the website material, as users should now leverage the VSCode IDE option.
The CloudFormation template for Cloud9 still remains and will be cleaned up at a point in the future.
N/A

chore: Removed Cloud9 from documentation

---

website/docs/fundamentals/storage/efs/deployment-with-efs.md
website/docs/fundamentals/storage/efs/deployments.md
website/docs/fundamentals/storage/efs/efs-csi-driver.md
website/docs/fundamentals/storage/efs/index.md

Makes various language fixes to the EFS lab.
N/A

update: Various language fixes to EFS lab

---

manifests/modules/automation/controlplanes/ack/.workshop/cleanup.sh
manifests/modules/automation/controlplanes/ack/.workshop/terraform/main.tf
manifests/modules/automation/controlplanes/ack/.workshop/terraform/outputs.tf
website/docs/automation/controlplanes/ack/how-it-works.md
website/docs/automation/controlplanes/ack/index.md
website/docs/automation/controlplanes/ack/introduction.md

This PR added a web page that illustrates how to install the ACK DynanmoDB controller via helm chart. It also removed a section of  terraform file related to installing the ACK controller. It will give users more insight in to what is being done.
This PR solves part of the #863 issue (Changes to labs to manually install relevant components), specifically the section  [Automation] ACK - Install ACK via the helm charts. 
Fixes #
It fixes the description on the page of How does ACK work. 

update: Install ACK with helm chart

---

website/docs/observability/opensearch/access-opensearch.md

This PR removes the unneccesary and potentially destructive use of `tr -d '"'` to remove enclosing double-quotes from a json-string.
This might be destructive, because tr will remove *all* quotes, not only the enclosing ones and will not honor JSON escaped quotes.
Check:
`jq -cn '$ARGS.named' --arg test 'string_with"quotes"' | jq .test | tr -d '"'`
vs
`jq -cn '$ARGS.named' --arg test 'string_with"quotes"' | jq -r .test`

fix: remove unnecessary use of `tr` in access-opensearch.md

---

website/docs/autoscaling/workloads/cluster-proportional-autoscaler/install.md

Adds a note to the Cluster Proportional Autoscaling lab to reference the capability of the related EKS addon to easily provide autoscaling.
Fixes #1048

update: Added note related to CoreDNS autoscaling

---

manifests/modules/networking/securitygroups-for-pods/.workshop/terraform/preprovision/main.tf

There seems to be cases where the RDS final snapshot gets created when cleaning up the SG for Pods lab due to missing IAM permissions. This does not seem to happen in the automated tests.
This PR explicitly disables the final snapshot instead of changing the IAM permissions.
Fixes #1201

fix: Skip final RDS snapshot in SG for Pods

---

lab/iam/policies/ec2.yaml

This PR resolves the IAM issue reported here https://github.com/aws-samples/eks-workshop-v2/issues/1106
Without this change the following command fails which makes learning about EFS incredibly frustrating. 
```
prepare-environment fundamentals/storage/efs
```
Fixes # https://github.com/aws-samples/eks-workshop-v2/issues/1106

fix: adds missing permsions to the 'eks-workshop-ide-ec2' IAM policy

---

website/docs/networking/vpc-lattice/setup.md

Updating the VPC Lattice controller to 1.1.0 requires that we separately install the Gateway API CRDs.
N/A

fix: Now need to install CRDs in VPC Lattice lab

---

lab/scripts/installer.sh

This change pulls eksctl from it's new home on eksctl.io and updates it to 0.202.0
None, sorry :)
Tested using `make create-infrastructure` and `make destroy-infrastructure`
Happy to run additional tests.
- [x ] My content adheres to the style guidelines
- [x ] The PR has meaningful title and description of the changes that will be included in the workshop release notes

chore: Get eksctl from eksctlio

---

website/docs/autoscaling/compute/karpenter/consolidation.md

Previous explanation regarding WhenEmptyOrUnderutilized read odd.
Fixes #

fix: Better verbiage for WhenEmptyOrUnderutilized in Karpenter lab

---

website/src/components/HomepageBanner/index.js
website/src/components/HomepageBanner/styles.module.css
website/src/pages/index.js

Adding a homepage promotion banner to promote EKS-related events on the eksworkshop.com home page. Should not affect in-person events.

feat: Banner promotions on eksworkshop.com homepage

---

manifests/modules/observability/logging/pods/.workshop/terraform/main.tf
manifests/modules/observability/oss-metrics/.workshop/terraform/main.tf
manifests/modules/security/secrets-manager/.workshop/terraform/main.tf

There are still a few modules that use the old v4.X version of EKS Blueprints, which is no longer maintained. This PR migrates these references to either the new blueprints addons repository or installs the chart more directly.
Fixes #

chore: Removed old EKS Blueprints Terraform references

---

website/docs/networking/eks-hybrid-nodes/index.md

EKS Hybrid Nodes module preview was showing ::required-time because the description frontmatter is missing.
Fixes #
- [ x] My content adheres to the style guidelines
- [ x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
- [x ] The PR has meaningful title and description of the changes that will be included in the workshop release notes

fix: Add missing description to frontmatter for EKS Hybrid Nodes module

---

website/docs/autoscaling/compute/karpenter/consolidation.md

Fix for grepping Karpenter logs due to node disruption.

fix: karpenter log grep updated in Karpenter lab

---

website/docs/autoscaling/compute/karpenter/consolidation.md
website/docs/autoscaling/compute/karpenter/tests/hook-grep.sh

Test suite now checks for karpenter disruption log. If it changes in the future, test suite should fail.

fix: test suite checks for karpenter disruption log

---

manifests/.workshop/terraform/base.tf

chore(deps): bump terraform to 5.95

---

manifests/modules/networking/eks-hybrid-nodes/.workshop/cleanup.sh

The EKS Hybrid nodes module is failing cleanup if the cloud bursting scenario is never run. Using this function fixes that.
EKS Hybrid Nodes module fails cleanup if the cloud bursting scenario is never run. This is because cleanup was trying to delete a CRD that is not installed.
Fixes #1357
- [ x] My content adheres to the style guidelines
- [ x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
- [x ] The PR has meaningful title and description of the changes that will be included in the workshop release notes

fix: Use delete-all-if-crd-exists for cleanup

---

website/docs/security/cluster-access-management/managing.md

Fixes a command that is returning an error:
`NODE_ROLE=$(aws eks list-access-entries --cluster $EKS_CLUSTER_NAME --output text | awk '/Node/ {print $2}')
aws eks describe-access-entry --cluster $EKS_CLUSTER_NAME --principal-arn $NODE_ROLE
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
aws help
aws <command> help
aws <command> <subcommand> help
Unknown options: arn:aws:iam::273073574926:role/eksctl-eks-workshop-nodegroup-defa-NodeInstanceRole-jD2CUSiBTxMD`
The aws command returns 2 roles arn and it causes the error:
`aws eks list-access-entries --cluster $EKS_CLUSTER_NAME --output text | awk '/Node/ {print $2}'
arn:aws:iam:::role/eksctl-eks-workshop-cluster-HybridNodesSSMRole-gTfzyVPtHaSA …

fix: command is returning error

---

website/docs/fundamentals/managed-node-groups/basics/affinity/index.md

* Changed incorrect term 'pod' to 'node'.
* Formatted pod names
Fixes # N/A

fix: Minor edits to MNG affinity docs

---

website/docs/security/secrets-management/secrets-manager/ascp.md

The command shown in the docs assumes the secrets store csi driver is installed in a namespace that is wrong. The driver is currently installed in kube-system namespace. 
https://github.com/aws-samples/eks-workshop-v2/issues/1446
Fixes #
Changed the namespace in the command. 

docs: Update ascp.md

---

website/docs/fundamentals/exposing/ingress/external-dns.md

```
ec2-user:~/environment:$ kubectl -n ui exec -it \
deployment/ui -- curl -i http://ui.retailstore.com/actuator/health/liveness
HTTP/1.1 200 OK
Date: Wed, 11 Jun 2025 15:22:58 GMT
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 15
Connection: keep-alive
Set-Cookie: SESSIONID=8a73565b-efe1-4ecf-9fa8-8f3efce7e2e4
{"status":"UP"}ec2-user:
```
updated to:
```
ec2-user:~/environment:$ kubectl -n ui exec -it \
deployment/ui -- bash -c "curl -i http://ui.retailstore.com/actuator/health/liveness; echo"
HTTP/1.1 200 OK
Date: Wed, 11 Jun 2025 15:31:30 GMT
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 15
Connection: keep-alive
Set-Cookie: SESSIONID=ce1b998f-b9c0-4865-8316-99f6e1ac6566
{"status":"UP"}
ec2-user:~/environment:$ 
```
Fixes #
By …

Update external-dns.md for new line after output

---

website/docs/networking/eks-hybrid-nodes/cloud-bursting.md

This adds a wait for all kyverno pods to come up before applying policy.
The wait was in there previously before the workload, but after policy.
- [ x] My content adheres to the style guidelines
- [ x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)
- [ x] The PR has meaningful title and description of the changes that will be included in the workshop release notes

update: Ensure Kyverno is ready before applying policy

---

website/src/components/GlobalNotification/index.js
website/src/components/GlobalNotification/styles.module.css
website/src/config/notification.json
website/src/theme/Root/index.js

Used for CTAs, only appears on eksworkshop.com. Configured to be false by default. Only needs to be dismissed once. On stable branch, we update `website/src/config/notification.json` to have `enabled: true`

feat: Add dismissable notification with configurable content

---

hack/publish-content.sh
website/docusaurus.config.js
website/src/components/GlobalNotification/index.js
website/src/config/notification.json

builds on #1503. realized that the current implementation will lead to merge failure when cutting our monthly release, so let's rely on an env based approach.

fix: read build env to show/hide notification

---

manifests/modules/troubleshooting/pod/.workshop/terraform/deployment_image.yaml
manifests/modules/troubleshooting/pod/.workshop/terraform/main.tf
website/docs/troubleshooting/pod/private_image.md
website/docs/troubleshooting/pod/public_image.md

Migrate from using the template provider to the templatefile function as noted in the provider docs. That provider is deprecated https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file. 
Also updated the ecr image generation for one scenario to use containerd to push the image to ECR instead of docker.
- [x ] My content adheres to the style guidelines

update: updating to templatefile function instead of template provider for troubleshooting module
